name: user_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  get: ^4.6.5
  google_fonts: ^5.1.0
  expandable: ^5.0.1
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  http: ^1.1.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  assets:
    - assets/

  
